FROM centos:8

# set the github runner version
ARG RUNNER_VERSION="2.278.0"

LABEL org.opencontainers.image.authors="Michael Herman <michael@mherman.org>, Piotr Parczewski <piotr@stackhpc.com>"

RUN dnf update -y && \
    dnf install -y gcc git vim python3-pyyaml python3-virtualenv libffi-devel sudo which openssh-server jq && \
    dnf clean all && useradd -m docker

# cd into the user directory, download and unzip the github actions runner
RUN cd /home/docker && mkdir actions-runner && cd actions-runner \
    && curl -O -L https://github.com/actions/runner/releases/download/v${RUNNER_VERSION}/actions-runner-linux-x64-${RUNNER_VERSION}.tar.gz \
    && tar xzf ./actions-runner-linux-x64-${RUNNER_VERSION}.tar.gz \
    && rm -f ./actions-runner-linux-x64-${RUNNER_VERSION}.tar.gz

# install some additional dependencies
RUN chown -R docker ~docker && /home/docker/actions-runner/bin/installdependencies.sh

# copy over the start.sh script
COPY start.sh start.sh

# since the config and run script for actions are not allowed to be run by root,
# set the user to "docker" so all subsequent commands are run as the docker user
USER docker

# set the entrypoint to the start.sh script
ENTRYPOINT ["./start.sh"]
